### ISSUE TITLE
failed to clone

### ISSUE THREAD

**Issue by iceberg1369** [ngohaibac/Quectel_SC20_Linux_Build#1]
Hello, I have been trying to clone the sc20_linux, but following command fails.

      git clone ssh://git@gitlab.quectel.com:2222/quectel_smart/sc20_linux.git

    Cloning into 'sc20_linux'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.

**Comment by bacnh85** [comment]
Hi,

In order to access SC20 Linux SDK, you need to communicate with respective sales in your country.
